# Generated by Django 5.2.7 on 2025-10-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Reciclagem', 'Reciclagem'), ('Transporte', 'Transporte Sustentável'), ('EconomiaRecursos', 'Economia de Recursos'), ('DescarteCorreto', 'Descarte Correto'), ('PlantioArvore', 'Plantio de Árvore')], help_text='Tipo de ação sustentável', max_length=50, unique=True, verbose_name='Nome da Ação')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da ação', verbose_name='Descrição')),
                ('base_points', models.IntegerField(default=10, help_text='Quantidade de pontos que esta ação gera', verbose_name='Pontos Base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ação',
                'verbose_name_plural': 'Tipos de Ações',
                'db_table': 'action_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Água', 'Água'), ('Energia', 'Energia')], max_length=20, verbose_name='Tipo de Conta')),
                ('consumption_value', models.DecimalField(decimal_places=2, help_text='Consumo em m³ (água) ou kWh (energia)', max_digits=10, verbose_name='Valor de Consumo')),
                ('value_rs', models.DecimalField(decimal_places=2, help_text='Valor da conta em reais', max_digits=10, verbose_name='Valor em R$')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto')),
                ('photo_file', models.ImageField(blank=True, help_text='Upload da foto da conta', null=True, upload_to='bills/%Y/%m/', verbose_name='Foto da Conta')),
                ('month', models.IntegerField(help_text='Mês de referência (1-12)', verbose_name='Mês')),
                ('year', models.IntegerField(help_text='Ano de referência', verbose_name='Ano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'verbose_name': 'Registro de Conta',
                'verbose_name_plural': 'Registros de Contas',
                'db_table': 'bill_records',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da ação realizada', verbose_name='Descrição')),
                ('proof_url', models.URLField(blank=True, help_text='Link para foto/vídeo de comprovação', max_length=500, null=True, verbose_name='URL da Comprovação')),
                ('proof_file', models.FileField(blank=True, help_text='Upload de foto/vídeo de comprovação', null=True, upload_to='actions/proofs/%Y/%m/%d/', verbose_name='Arquivo de Comprovação')),
                ('location', models.CharField(blank=True, help_text='Local onde a ação foi realizada', max_length=200, null=True, verbose_name='Localização')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20, verbose_name='Status')),
                ('points_awarded', models.IntegerField(default=0, help_text='Quantidade de pontos atribuídos por esta ação', verbose_name='Pontos Concedidos')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
            ],
            options={
                'verbose_name': 'Ação do Usuário',
                'verbose_name_plural': 'Ações dos Usuários',
                'db_table': 'user_actions',
                'ordering': ['-date'],
            },
        ),
    ]
