# Generated by Django 5.2.7 on 2025-10-23 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_actions', to='actions.actiontype', verbose_name='Tipo de Ação'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='billrecord',
            unique_together={('user', 'type', 'month', 'year')},
        ),
    ]
