# Generated by Django 5.2.7 on 2025-10-23 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Quantidade de tokens (positivo para crédito, negativo para débito)', verbose_name='Quantidade')),
                ('type', models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito')], max_length=20, verbose_name='Tipo de Transação')),
                ('source', models.CharField(choices=[('Ação', 'Ação Sustentável'), ('Troca', 'Troca por Recompensa'), ('Bônus', 'Bônus'), ('Administrativo', 'Ajuste Administrativo')], help_text='Origem dos tokens', max_length=30, verbose_name='Origem')),
                ('reference_id', models.IntegerField(blank=True, help_text='ID da ação ou recompensa relacionada', null=True, verbose_name='ID de Referência')),
                ('description', models.TextField(blank=True, help_text='Descrição da transação', verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('balance_after', models.IntegerField(default=0, help_text='Saldo do usuário após esta transação', verbose_name='Saldo Após')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação de Token',
                'verbose_name_plural': 'Transações de Tokens',
                'db_table': 'token_ledger',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='token_ledge_user_id_6bc034_idx'), models.Index(fields=['type', '-date'], name='token_ledge_type_03cb0f_idx')],
            },
        ),
    ]
